### ISSUE TITLE
How to use formdata?

### ISSUE THREAD

**Issue by simman** [tryolabs/fetch-it#7]
How to use formdata?

**Comment by dig3** [comment]
I just tried some code to check how `FormData` should work with `fetch-it` and I realized that probably isn't working :(.

Code:
```javascript
let form = document.forms[0]
// make it an array
form = [].slice.call(form)
console.log(form.filter(e => e.hasAttribute('name')).map(e => `${e.getAttribute('name')}=${e.value}`).join('&')) // => "q=hola"

let fd = new FormData(form)
console.log(JSON.stringify(fd) // => "{}"
```

So I guess that if you pass a `FormData` object to `post`, `put` or `patch` it won't work since https://github.com/tryolabs/fetch-it/blob/master/src/fetch-it.js#L24 . Maybe you can specify a `body` in the `options` object instead of passing a `data` object.

I didn't test it in fetch-it yet, but I will.

**Comment by dig3** [comment]
Hey @simman, did it worked passing `FormData` in `options.body`? Anyways I think I'll have to fix passing a `FormData` object in the `data` param.

**Comment by simman** [comment]
I am used in ReactNative, I have modified the source code

deleted :  （Because it doesn't work）

```
import 'isomorphic-fetch';
```

modified: 

```
const DEFAULT_CONFIG = {bodyType: 'formData'};
```

```
constructor(config) {
    this.config = config || DEFAULT_CONFIG;
    this.middlewares = [];
  }
```

```
if (!!data) {
    if (options.bodyType == 'json') {
      options.body = global.JSON.stringify(data);
    } else if (options.bodyType == 'formData') {
      options.body = querystring.stringify(data);
    } else {
      options.body = data;
    }
}
```
